### ISSUE TITLE
How to use qt5 to visualise the project when I use geant4_pybind？

### ISSUE THREAD

**Issue by Road-to-Serfdom** [HaarigerHarald/geant4_pybind#12]

**Comment by HaarigerHarald** [comment]
The pre-compiled wheels only contain the OpenGL visualization, if you need QT then you'll have to build Geant4 from source with QT visualization and afterwards build geant4_pybind using your build of Geant4:

https://geant4-userdoc.web.cern.ch/UsersGuides/InstallationGuide/html/installguide.html#buildandinstall

Note: Geant4 has to be build with option `GEANT4_BUILD_TLS_MODEL=global-dynamic` for the bindings to work.

**Comment by Road-to-Serfdom** [comment]
What you mean is that only by compiling the source to install geant4_pybind, I can use QT5 for visualization. Right?

**Comment by HaarigerHarald** [comment]
Yes, but first you have to make sure that the build of Geant4 you are linking the bindings against contains QT visualization (i.e. the `GEANT4_USE_QT` cmake flag must be set). The bindings you link against your Geant4 build will then automatically be a able to use it.

**Comment by Road-to-Serfdom** [comment]
When I try to install geant4_pybind by buiding from the sorce, something went wrong.The error messages are as follows:
Traceback (most recent call last):
        File "/home/maga/geant4_pybind/doc/generate_stubs.py", line 12, in <module>
          module = importlib.util.module_from_spec(spec)
        File "<frozen importlib._bootstrap>", line 571, in module_from_spec
        File "<frozen importlib._bootstrap_external>", line 1176, in create_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      ImportError: /home/maga/geant4/lib/libG4geometry.so: cannot allocate memory in static TLS block
      Traceback (most recent call last):
        File "/home/maga/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/maga/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/maga/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 100, in <module>
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-un98w4iq/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 79, in build_extension
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python3', 'doc/generate_stubs.py', 'geant4_pybind', '/home/maga/geant4_pybind/build/lib.linux-x86_64-cpython-310/geant4_pybind.cpython-310-x86_64-linux-gnu.so']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for geant4-pybind
Failed to build geant4-pybind
ERROR: Could not build wheels for geant4-pybind, which is required to install pyproject.toml-based projects

**Comment by HaarigerHarald** [comment]
Did you build Geant4 with `GEANT4_BUILD_TLS_MODEL=global-dynamic` ? If so, mind sharing the cmake command you used?

**Comment by Road-to-Serfdom** [comment]
I use ccmake command to build the source of Geant4, but there's no option called GEANT4_BUILD_TLS_MODEL.

**Comment by HaarigerHarald** [comment]
There is a way to see all CMAKE options and not just the standard ones with ccmake, I think it's CTRL + A or something similar.

**Comment by Road-to-Serfdom** [comment]
I've solved this problem on Ubuntu system by using the GUI surface of cmake and clicking "advanced" bottom.However, it is said in the official installation guide that "GEANT4_BUILD_TLS_MODEL" option is only in Unix system.Just like mentioned above, I can't find this option when I do the same thing in Windows system.So how can I solve this problem in Windwos system?

**Comment by Road-to-Serfdom** [comment]
Just as what I said in the last message, there is no option called GEANT4_BUILD_TLS_MODEL. And here are the error messages on Windows system:
Traceback (most recent call last):
        File "C:\Users\Adolf\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Adolf\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Adolf\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 100, in <module>
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\Adolf\AppData\Local\Temp\pip-build-env-bew5myrp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 74, in build_extension
        File "C:\Users\Adolf\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for geant4-pybind
Failed to build geant4-pybind
ERROR: Could not build wheels for geant4-pybind, which is required to install pyproject.toml-based projects

**Comment by HaarigerHarald** [comment]
Without any error message from cmake it's hard to tell what went wrong, you could try installing with:

    python3 setup.py build_ext install --user

for a more detailed error message.

**Comment by Road-to-Serfdom** [comment]
Here is the CmakeError file.
[CMakeError.log](https://github.com/HaarigerHarald/geant4_pybind/files/10860197/CMakeError.log)

**Comment by HaarigerHarald** [comment]
The prebuilt wheels now contain Qt5 visualization.
