### ISSUE TITLE
Preliminary support for Geant4 11.2

### ISSUE THREAD

**Issue by vp1981** [HaarigerHarald/geant4_pybind#20]
Hello.
I made a patch to compile `geant4_pybind` for Geant4 11.2.

I was able to successfully compile the code, but then it failed at the linking stage:
```
Traceback (most recent call last):
  File "/usr/bin/pybind11-stubgen", line 33, in <module>
    sys.exit(load_entry_point('pybind11-stubgen==2.4.2', 'console_scripts', 'pybind11-stubgen')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pybind11_stubgen/__init__.py", line 317, in main
    run(
  File "/usr/lib/python3.11/site-packages/pybind11_stubgen/__init__.py", line 356, in run
    QualifiedName.from_str(module_name), importlib.import_module(module_name)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: generic_type: type "G4TouchableHistory" is already registered!
```

I'm not sure what the reason is, but I hope someone can give me a hint on what might be wrong here.

P.S. I'm using Archlinux with python 3.11.6, pybind11-stubgen 2.4.2.

P.P.S. I have attached the patch to the issue.

**Comment by vp1981** [comment]
I don't get why github didn't attach the file, so I'm giving a link to the patch: https://git.sr.ht/~vp1981/pkgbuild/blob/master/python-geant4/geant4-11.2.patch

**Comment by vp1981** [comment]
I was able to resolve the issue and updated the patch.

It turned out that in version 11.2 `G4VTouchable` is an "alias" of `G4TouchableHistory`.

There are quite a few of changes in Geant4 11.2: removed classes, one class moved to "private" section, changes in function signatures, function return types. There may be an unintentional property change, at least in two functions (missing `override`).

**Comment by HaarigerHarald** [comment]
I was in the process of doing it myself on Wednesday, but noticed that I might need more time, especially to ensure that it remains backwards compatible. Hope I'll finish it by the end of the coming week.

**Comment by vp1981** [comment]
Since there are a number of pretty drastic changes, I doubt whether it is worth maintaining backwards compatibility. Perhaps it would be much easier to make a tagged commit (and release a new beta version) compatible with Geant4 11.1.X, and then support Geant4 11.2 onwards.
